//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dodatkowe_Oplaty
    {
        public int ID_Oplaty { get; set; }
        public int ID_Goscia { get; set; }
        public int ID_Uslugi { get; set; }
        public System.DateTime Data_Wykonania { get; set; }
    
        public virtual Goscie Goscie { get; set; }
        public virtual Dodatkowe_Uslugi Dodatkowe_Uslugi { get; set; }
    }
}
