//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Rezerwacji
    {
        public int ID_Rezerwacja { get; set; }
        public int ID_Pokoju { get; set; }
        public int ID_Goscia { get; set; }
        public int Obslugiwany_przez { get; set; }
        public System.DateTime Rezerwacja_Od { get; set; }
        public System.DateTime Rezerwacja_Do { get; set; }
    
        public virtual Goscie Goscie { get; set; }
        public virtual Pokoje Pokoje { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
